import { StyleSheet, Platform, StatusBar, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

export const CARD_WIDTH = screenWidth - 40;
export const GAP = 16;
export const SCROLL_WIDTH = CARD_WIDTH + GAP;

/**
 * getDynamicStyles — Tema renklerine (colors) göre tüm MyPlants ekranı
 * ve alt bileşenlerinin stillerini üretir.
 * colors nesnesi: Colors.dark veya Colors.light (src/theme/colors.js)
 */
const getDynamicStyles = (colors) => StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: colors.background, paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0 },
    scrollContent: { paddingTop: 10, paddingBottom: 40 },
    paddedSection: { paddingHorizontal: 20 },
    header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
    headerLogoContainer: { flexDirection: 'row', alignItems: 'center' },
    headerTitleMain: { fontSize: 28, fontWeight: '800', color: colors.textMain, letterSpacing: -0.8 },
    headerTitleAI: { color: '#2ECC71', fontWeight: '900', textShadowColor: 'rgba(46, 204, 113, 0.4)', textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 8 },
    headerIconsRow: { flexDirection: 'row', alignItems: 'center' },
    themeToggleContainer: { marginRight: 16 },
    bellIconContainer: { position: 'relative' },
    notificationDot: { position: 'absolute', top: 2, right: 2, width: 10, height: 10, borderRadius: 5, backgroundColor: colors.accent, borderWidth: 2, borderColor: colors.background },

    carouselContainer: { marginBottom: 16, alignItems: 'center' },

    card: {
        width: CARD_WIDTH,
        height: 210,
        backgroundColor: colors.card,
        borderRadius: 24,
        padding: 24,
        position: 'relative',
    },

    weatherBgVideo: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, width: CARD_WIDTH, height: 210, borderRadius: 24 },
    weatherOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.3)', zIndex: 1, borderRadius: 24 },
    weatherTextWhite: { color: '#FFFFFF', textShadowColor: 'rgba(0,0,0,0.5)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 6 },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
    cardHeaderTitle: { color: colors.textMuted, fontSize: 13, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1 },
    cardMainText: { color: colors.textMain, fontSize: 26, fontWeight: 'bold', letterSpacing: 0.5 },
    cardFooter: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
    cardFooterMuted: { color: colors.textMuted, fontSize: 14, fontWeight: '500' },
    weatherDataContainer: { flexDirection: 'column' },
    weatherDataRow: { flexDirection: 'row', alignItems: 'center' },
    weatherTempText: { fontSize: 34, fontWeight: 'bold', color: colors.textMain },
    weatherDescText: { fontSize: 16, fontWeight: '600', color: '#EBEBEB', marginTop: -4, marginLeft: 2, textShadowColor: 'rgba(0,0,0,0.5)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 4 },
    weatherLoadingText: { fontSize: 16, fontWeight: '500', color: colors.textMuted },

    dotsContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 30 },
    dotActive: { width: 28, height: 5, borderRadius: 3, backgroundColor: colors.accent, marginHorizontal: 3 },
    dotInactive: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.navInactive, marginHorizontal: 3 },
    actionsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 30 },
    actionContainer: { alignItems: 'center', width: '23%' },
    actionCircle: { width: 60, height: 60, borderRadius: 30, justifyContent: 'center', alignItems: 'center', marginBottom: 8, shadowColor: colors.accent, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 6, elevation: 2 },
    actionLabel: { textAlign: 'center', fontSize: 12, color: colors.textMain, fontWeight: '600', lineHeight: 16 },
    logHeaderContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 16 },
    logHeaderTitle: { fontSize: 20, fontWeight: 'bold', color: colors.textMain },
    seeAllText: { fontSize: 14, color: colors.accent, fontWeight: 'bold' },
    logList: { width: '100%' },
    plantItemContainer: { flexDirection: 'row', backgroundColor: colors.card, borderRadius: 24, padding: 16, alignItems: 'center', marginBottom: 14 },
    plantImageWrapper: { width: 80, height: 80, marginRight: 24, position: 'relative' },
    plantImageStackBase: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: colors.navInactive, borderRadius: 16 },
    stackLayer1: { transform: [{ translateX: 6 }, { scaleY: 0.9 }], opacity: 0.35, zIndex: 2 },
    stackLayer2: { transform: [{ translateX: 12 }, { scaleY: 0.8 }], opacity: 0.15, zIndex: 1 },
    plantImageMain: { width: 80, height: 80, borderRadius: 16, zIndex: 3 },
    plantTextContainer: { flex: 1, minHeight: 80, justifyContent: 'space-between', paddingVertical: 2 },
    plantTitle: { fontSize: 18, fontWeight: 'bold', color: colors.textMain, marginBottom: 2 },
    plantSubtitle: { fontSize: 13, color: colors.textMuted, fontWeight: '500' },
    plantNeedsRow: { flexDirection: 'row', marginTop: 10 },
    needIconCircle: { width: 36, height: 36, borderRadius: 18, borderWidth: 1.5, justifyContent: 'center', alignItems: 'center' },

    // Boş Liste Tasarımı
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 24,
        backgroundColor: colors.card,
        borderRadius: 24,
        borderWidth: 1,
        borderColor: colors.navInactive + '15',
        marginVertical: 10,
    },
    emptyText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.textMain,
        marginBottom: 4,
    },
    emptySubText: {
        fontSize: 12,
        color: colors.textMuted,
        textAlign: 'center',
        lineHeight: 18,
    },

    // Modal Stilleri
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: colors.card,
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        height: '85%',
        paddingTop: 16,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.navInactive + '20',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.textMain,
    },
    closeButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalScroll: {
        padding: 24,
        paddingBottom: 50,
    },
    dragHandleWrapper: {
        width: '100%',
        paddingTop: 14,
        paddingBottom: 12,
        alignItems: 'center',
        justifyContent: 'center',
        // iOS'ta dokunma alanını genişletmek için ekstra padding
        marginBottom: 2,
    },
    dragHandle: {
        width: 48,
        height: 5,
        borderRadius: 2.5,
        backgroundColor: colors.navInactive + '45',
    },
    modalImageContainer: {
        position: 'relative',
        width: '100%',
        height: 300,
        borderRadius: 24,
        overflow: 'hidden',
        marginBottom: 20,
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.navInactive + '15',
    },
    modalImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    imageFloatingBadge: {
        position: 'absolute',
        bottom: 12,
        left: 12,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.65)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 14,
    },
    imageFloatingBadgeText: {
        color: '#FFFFFF',
        fontSize: 13,
        fontWeight: 'bold',
    },
    zoomIconBadge: {
        position: 'absolute',
        top: 12,
        right: 12,
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalHeaderActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    deleteModalButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255, 59, 48, 0.08)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    zoomOverlayAbsolute: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.98)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10000,
    },
    zoomCloseButton: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 60 : 40,
        right: 24,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10010,
    },
    zoomImage: {
        width: '100%',
        height: '80%',
    },
    sectionCard: {
        backgroundColor: colors.card,
        borderRadius: 24,
        padding: 18,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.navInactive + '15',
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 14,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.navInactive + '15',
        paddingBottom: 8,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.textMain,
        letterSpacing: -0.2,
    },
    rowLabelGroup: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.navInactive + '08',
    },
    detailLabel: {
        fontSize: 14,
        color: colors.textMuted,
        fontWeight: '500',
    },
    detailValue: {
        fontSize: 14,
        fontWeight: 'bold',
        color: colors.textMain,
    },
    treatmentCard: {
        backgroundColor: colors.accent,
        padding: 20,
        borderRadius: 24,
        shadowColor: colors.accent,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 4,
    },
    treatmentTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    treatmentTitle: {
        fontSize: 17,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    treatmentText: {
        fontSize: 14,
        color: '#F4FBF4',
        lineHeight: 22,
        fontWeight: '500',
    },

    // ─────────────────────────────────────────────────
    // Fidan Bağışı Stilleri (Premium)
    // ─────────────────────────────────────────────────
    donationBannerPremium: {
        backgroundColor: colors.card,
        borderRadius: 24,
        padding: 24,
        alignItems: 'center',
        marginBottom: 24,
        borderWidth: 1.5,
        borderColor: 'rgba(46, 204, 113, 0.25)',
        shadowColor: '#2ECC71',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 3,
    },
    donationBannerTitlePremium: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.textMain,
        textAlign: 'center',
        marginBottom: 8,
        letterSpacing: -0.5,
    },
    donationBannerTextPremium: {
        fontSize: 13,
        color: colors.textMuted,
        textAlign: 'center',
        lineHeight: 20,
        fontWeight: '500',
    },
    selectorCardPremium: {
        backgroundColor: colors.background,
        borderRadius: 22,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: colors.navInactive + '15',
    },
    fieldLabelPremium: {
        fontSize: 12,
        fontWeight: 'bold',
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        marginBottom: 8,
    },
    unitPriceBadge: {
        fontSize: 12,
        fontWeight: '700',
        color: '#2ECC71',
        backgroundColor: 'rgba(46, 204, 113, 0.1)',
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 8,
    },
    counterRowPremium: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: colors.card,
        borderRadius: 16,
        paddingVertical: 8,
        paddingHorizontal: 8,
        borderWidth: 1,
        borderColor: colors.navInactive + '10',
    },
    counterBtnPremium: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: '#2ECC71',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#2ECC71',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 2,
    },
    counterValuePremium: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.textMain,
    },
    checkoutSummaryCard: {
        backgroundColor: 'rgba(46, 204, 113, 0.08)',
        borderRadius: 20,
        padding: 20,
        marginBottom: 26,
        borderWidth: 1.5,
        borderColor: 'rgba(46, 204, 113, 0.25)',
    },
    checkoutSummaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    checkoutSummaryLabel: {
        fontSize: 11,
        fontWeight: '800',
        color: '#2ECC71',
        letterSpacing: 1,
        marginBottom: 2,
    },
    checkoutSummarySubLabel: {
        fontSize: 14,
        color: colors.textMuted,
        fontWeight: '600',
    },
    checkoutSummaryTotal: {
        fontSize: 26,
        fontWeight: 'bold',
        color: '#2ECC71',
        letterSpacing: -0.5,
    },
    formSectionTitle: {
        fontSize: 13,
        fontWeight: '800',
        color: colors.textMain,
        letterSpacing: 1,
        marginBottom: 16,
        textTransform: 'uppercase',
    },
    inputWrapperPremium: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 18,
        paddingHorizontal: 16,
        height: 56,
        marginBottom: 22,
        borderWidth: 1.5,
        borderColor: colors.navInactive + '20',
    },
    inputWrapperPremiumHalf: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 18,
        paddingHorizontal: 14,
        height: 56,
        borderWidth: 1.5,
        borderColor: colors.navInactive + '20',
    },
    textInputPremium: {
        flex: 1,
        fontSize: 15,
        fontWeight: '600',
        height: '100%',
    },
    donateSubmitBtnPremium: {
        backgroundColor: '#2ECC71',
        height: 58,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#2ECC71',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
        elevation: 6,
        marginTop: 10,
    },
    donateSubmitBtnTextPremium: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    successContainerPremium: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
    },
    successTreeCirclePremium: {
        width: 110,
        height: 110,
        borderRadius: 55,
        backgroundColor: '#2ECC71',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#2ECC71',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
        elevation: 8,
    },
    successTitlePremium: {
        fontSize: 26,
        fontWeight: 'bold',
        color: colors.textMain,
        marginBottom: 4,
        letterSpacing: -0.5,
    },
    successSubTitlePremium: {
        fontSize: 16,
        fontWeight: '700',
        color: '#2ECC71',
        marginBottom: 24,
    },
    certificateSummaryCardPremium: {
        width: '100%',
        backgroundColor: colors.card,
        borderRadius: 24,
        padding: 24,
        alignItems: 'center',
        marginBottom: 24,
        borderWidth: 1.5,
        borderColor: colors.navInactive + '15',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    certSummaryLabelPremium: {
        fontSize: 11,
        color: colors.textMuted,
        fontWeight: '800',
        letterSpacing: 1.5,
        marginBottom: 6,
    },
    certSummaryNamePremium: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.textMain,
        textAlign: 'center',
    },
    dividerPremium: {
        width: '80%',
        height: 1,
        backgroundColor: colors.navInactive + '15',
        marginVertical: 16,
    },
    certSummaryDetailsPremium: {
        fontSize: 16,
        color: colors.textMain,
        fontWeight: '700',
        marginBottom: 4,
    },
    certSummarySubDetailsPremium: {
        fontSize: 13,
        color: colors.textMuted,
        fontWeight: '600',
        marginBottom: 16,
    },
    certPaymentBadgePremium: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(46, 204, 113, 0.1)',
        paddingVertical: 6,
        paddingHorizontal: 14,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(46, 204, 113, 0.25)',
    },
    certPaymentBadgeTextPremium: {
        fontSize: 13,
        color: '#2ECC71',
        fontWeight: 'bold',
    },
    successTextPremium: {
        fontSize: 14,
        color: colors.textMuted,
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 30,
        paddingHorizontal: 12,
        fontWeight: '500',
    },
    successCloseBtnPremium: {
        backgroundColor: colors.textMain,
        height: 56,
        borderRadius: 20,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.textMain,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 10,
        elevation: 3,
    },
    successCloseBtnTextPremium: {
        color: colors.background,
        fontSize: 16,
        fontWeight: 'bold',
    },

    // Eski / Kullanılmayan stiller (geriye dönük uyumluluk)
    donationBanner: {
        backgroundColor: '#2ECC71',
        borderRadius: 24,
        padding: 24,
        alignItems: 'center',
        marginBottom: 24,
    },
    donationBannerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFFFFF',
        textAlign: 'center',
        marginBottom: 8,
    },
    donationBannerText: {
        fontSize: 13,
        color: '#E8F8F5',
        textAlign: 'center',
        lineHeight: 18,
    },
    fieldLabel: {
        fontSize: 12,
        fontWeight: 'bold',
        color: colors.textMuted,
        marginBottom: 10,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    foundationRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 24,
    },
    foundationCard: {
        width: '31%',
        backgroundColor: colors.background,
        borderWidth: 1.5,
        borderColor: colors.navInactive + '15',
        borderRadius: 16,
        paddingVertical: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    foundationText: {
        fontSize: 11,
        color: colors.textMuted,
        marginTop: 6,
        textAlign: 'center',
    },
    counterRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.background,
        borderRadius: 20,
        paddingVertical: 10,
        paddingHorizontal: 20,
        alignSelf: 'center',
        marginBottom: 24,
        borderWidth: 1,
        borderColor: colors.navInactive + '10',
    },
    counterBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.card,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.navInactive + '15',
    },
    counterValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.textMain,
        marginHorizontal: 30,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 18,
        paddingHorizontal: 16,
        height: 54,
        marginBottom: 30,
        borderWidth: 1,
        borderColor: colors.navInactive + '15',
    },
    inputWrapperHalf: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 18,
        paddingHorizontal: 12,
        height: 54,
        borderWidth: 1,
        borderColor: colors.navInactive + '15',
    },
    cardDetailsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 30,
    },
});

export default getDynamicStyles;
